FROM ubuntu:16.04

RUN apt-get update --fix-missing
COPY ./ ./
RUN cat apt.txt | xargs apt-get install -y
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENTRYPOINT jupyter notebook --allow-root --NotebookApp.token='' --i 0.0.0.0 --no-browser
